[project]
name = "display"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.2",
    "pillow>=11.1.0",
    "pre-commit>=4.1.0",
    "spidev>=3.6",
]
